server_name: $SERVER_NAME

http_port: 8222

jetstream: enabled

jetstream {
  store_dir: $JETSTREAM_STORE_DIR
}

accounts {
  HA {
      users = [
        {user: admin, password: "$2a$11$5iDnTAXdsPUPIh00L1kiOeW06b0UNNB8VG3T6mQGCDNvtU1gy4ieW"}
        {nkey: "UA3X7PHBC2LE6BMCNJQHIVAD3KGQAX5523XHTB2WEZPOEKYMITAXA4X6"}
      ]
      exports: [
            {stream: crm_vendedor.>}
      ]
      jetstream: enabled
  }
}

cluster {
  name: cluster
  port: 6222
  routes = [
    $CLUSTER_ROUTES_SEED
  ]
}
